module ::= moduleclause (';' definitions|'where' '{' definitions '}')|'{' definitions '}'
definitions ::= definition (semicoli definitions?)?
definition ::= DOCUMENTATION definition?|topdefinition|visibledefinition
topdefinition ::= import|fixity operators|'native' 'module' typeclause interfaces 'where' '{' jtokens? '}'|publicdefinition
visibledefinition ::= (PRIVATE|PROTECTED|PUBLIC) publicdefinition|ABSTRACT datainit wheredef
publicdefinition ::= typedef|(datainit|INSTANCE insthead) wheredef|classdef|DERIVE insthead|localdef
classdef ::= CLASS ccontext ('=>' CONID tyvar)? wheredef
datadef ::= datainit wheredef
instdef ::= INSTANCE insthead wheredef
wheredef ::= ('where' '{' localdefs? '}')?
localdefs ::= dplocaldef (semicoli localdefs?)?
dplocaldef ::= DOCUMENTATION dplocaldef?|plocaldef
plocaldef ::= (PRIVATE|PROTECTED|PUBLIC)? localdef
localdef ::= annotation|'pure'? 'native' methodspec '::' sigexs|fundef
appex ::= appex? unex
lambdabody ::= '\' apats lambdabody|'->' expr
getfield ::= VARID (('<-'|'=') expr)?
getfields ::= getfield (',' getfields?)?
dodefs ::= lcqual (semicoli dodefs?)?
lcqual ::= gqual|expr '=' expr|LET '{' letdefs '}'
lcquals ::= lcqual (',' lcquals?)?
exprSS ::= expr (';' exprSS?)?
exprSC ::= expr (',' exprSC?)?
field ::= VARID ('=' expr)?
fields ::= field (',' fields?)?
term ::= qvarid|literal|'_'|qconid ('{' fields? '}')?|'(' ((commata|'!'|'?'|'-')?|SOMEOP expr?|binex (SOMEOP|'-')|expr (',' exprSC|';' exprSS)?) ')'|'[' ((expr '|' lcquals)?|exprSC ('..' expr?)?) ']'
primary ::= term|(DO '{' dodefs|qualifiers '{' (VARID ('?'|'='|'<-')|getfields)) '}'|primary '.' (VARID|SOMEOP|'!'|'?'|'{' (VARID ('?'|'='|'<-')|getfields) '}'|'[' expr ']')
unex ::= primary|('!'|'?') unex
apats ::= unex apats?
lambda ::= '\' apats lambdabody
wherelet ::= 'where' '{' letdefs? '}'
gqual ::= expr ('<-' expr)?
gquals ::= gqual (',' gquals?)?
guard ::= '|' gquals ('->'|'=') expr
guards ::= '|' gquals ('->'|'=') expr guards?
funhead ::= binex
fundef ::= binex ('=' expr|guards)|fundef 'where' '{' letdefs? '}'
letdef ::= annotation|fundef
letdefs ::= (annotation|fundef) (semicoli letdefs?)?
calts ::= calt (';' calts?)?
topex ::= ('if' expr ';'? 'then' expr ';'? 'else'|LET '{' letdefs '}' IN) expr|'case' expr OF '{' calts '}'|'\' apats lambdabody|appex
binex ::= binex (SOMEOP|'-') binex|'-'? topex
expr ::= binex ('::' (forall|rho))?
pattern ::= expr
calt ::= expr (('->'|'=') expr|guards)|calt 'where' '{' letdefs? '}'
aeq ::= '->'|'='
import ::= 'import' modulename1 (VARID? CONID)? importliste
importliste ::= ((VARID '(' importspecs|'(' importspecs?) ')'|PUBLIC importliste)?
importspecs ::= importspec (',' importspecs?)?
importspec ::= importitem (VARID|CONID|SOMEOP)?|PUBLIC importspec
importitem ::= qvarid|CONID '(' memspecs? ')'|qconid|SOMEOP|'!'|'?'
memspecs ::= memspec (',' memspecs?)?
memspec ::= (VARID|CONID|SOMEOP) (VARID|CONID|SOMEOP)?|PUBLIC memspec
alias ::= VARID|CONID|SOMEOP
annotation ::= annoitems '::' (forall|rho)
annoitems ::= annoitem (',' annoitems)?
nativedef ::= 'pure'? 'native' methodspec '::' sigexs
impurenativedef ::= 'native' methodspec '::' sigexs
methodspec ::= fitem ((rawnativename|SOMEOP|'!'|'?') ('{' tauSC? '}')?|'{' tauSC? '}')?
fitem ::= annoitem|'!'|'?'|'-'|SOMEOP
annoitem ::= VARID|'(' (SOMEOP|'!'|'?'|'-') ')'
datainit ::= 'data' CONID dvars? '=' (nativepur nativespec|dalts)|'newtype' CONID dvars? '=' dalt
dalts ::= dalt ('|' dalts)?
dalt ::= visdalt DOCUMENTATION?|DOCUMENTATION visdalt
visdalt ::= (PUBLIC|PRIVATE|PROTECTED)? strictdalt
strictdalt ::= ('!'|'?')? simpledalt
simpledalt ::= CONID ('{' conflds '}'|simpletypes)?
conflds ::= confld ((','|DOCUMENTATION) conflds?)?
confld ::= docs? fldids '::' (forall|rho)
sigexs ::= sigex ('|' sigexs)?
sigex ::= (forall|rho) (THROWS tauSC)?
typedef ::= 'type' CONID dvars? '=' (forall|rho)
sigma ::= forall|rho
derivedef ::= DERIVE insthead
insthead ::= icontext ('=>' tyname simpletype)?
icontext ::= qconid simpletype|'(' sicontexts ')'
sicontexts ::= qconid simpletype (',' sicontexts?)?
sicontext ::= qconid simpletype
contypes ::= simpletypes
nativespec ::= rawnativename ('{' tauSC? '}')?
gargs ::= '{' tauSC? '}'
moduledefinition ::= 'native' 'module' typeclause interfaces 'where' '{' jtokens? '}'
interfaces ::= (CLASS tauSC)?
typeclause ::= ('type' tau)?
rhofun ::= simpletypes ('->' rhofun)?
tauSB ::= tau ('|' tauSB)?
tauSC ::= tau (',' tauSC)?
tau ::= simpletypes ('->' tau)?|forall
simpletype ::= tyvar|tyname|'(' tau (',' tauSC|'|' tauSB)? ')'|'[' tau ']'
simpletypes ::= simpletype simpletypes?
tapp ::= simpletypes
rho ::= (simpletypes '=>')? rhofun
forall ::= FORALL boundvars ('.'|SOMEOP) rho
boundvars ::= VARID boundvars?
boundvar ::= VARID
ccontext ::= qconid tyvar|'(' scontexts ')'
tyname ::= qconid|'[' ']'|'(' (commata|'->')? ')'
commata ::= ',' commata?
moduleclause ::= docs? PROTECTED? 'module' modulename1|moduleclause words '(' qvarids ')'
docs ::= DOCUMENTATION (semicoli? docs)?
documentation ::= DOCUMENTATION
dvars ::= tyvar dvars?
elsex ::= ';'? 'else'
infix ::= fixity operators
fixity ::= (INFIX|INFIXL|INFIXR) INTCONST
fldids ::= fldid (',' fldids)?
fldid ::= (PUBLIC|PRIVATE)? strictfldid
jitem ::= rawnativename|SOMEOP|'!'|'?'
wheretokens ::= 'where' '{' jtokens? '}'
jtokens ::= (jtoken|'{' jtokens? '}') jtokens?
jtoken ::= VARID|CONID|QVARID|QCONID|CONID '.'|DOCUMENTATION|'module'|'import'|INFIX|INFIXR|INFIXL|'native'|'data'|'where'|CLASS|INSTANCE|ABSTRACT|'type'|TRUE|FALSE|'if'|'then'|'else'|'case'|OF|DERIVE|LET|IN|DO|FORALL|PRIVATE|PROTECTED|PUBLIC|'pure'|THROWS|'mutable'|INTCONST|STRCONST|LONGCONST|FLTCONST|DBLCONST|CHRCONST|'->'|'::'|'<-'|'=>'|'..'|SOMEOP|INTERPRET|','|'|'|'['|']'|'('|')'|'.'|'?'|'-'|';'|'!'|'='|'\'
scontexts ::= qconid tyvar (',' scontexts?)?
scontext ::= qconid tyvar
tyvar ::= VARID|'(' VARID '::' kind ')'
simplekind ::= SOMEOP|VARID|'(' kind ')'
kind ::= simplekind ('->' kind)?
literal ::= TRUE|FALSE|CHRCONST|STRCONST|INTCONST|BIGCONST|LONGCONST|FLTCONST|DBLCONST|REGEXP
mbdot ::= '.'|SOMEOP
modulename ::= modulename1
modulename1 ::= CONID|(varidkw '.'|CONID '.') modulename1
nativename ::= rawnativename
nativepur ::= ('pure'|'mutable')? 'native'
operators ::= (SOMEOP|VARID|'-') operators?
opstring ::= SOMEOP|VARID|'-'
qvarids ::= qvarop (',' qvarids)?
qvarop ::= (CONID '.' (CONID '.')?)? (VARID|'!'|'?')|SOMEOP
operator ::= SOMEOP
strictfldid ::= ('!'|'?')? VARID
plainfldid ::= VARID
qconid ::= (CONID '.' (CONID '.')?)? CONID
qualifiers ::= CONID '.' (CONID '.')?
qvarid ::= CONID '.' (CONID '.')? (VARID|'!'|'?')|VARID
rawnativename ::= (VARID|'module') ('.' rawnativename)?|CONID|CONID '.' rawnativename|STRCONST
semicoli ::= ';' semicoli?
thenx ::= ';'? 'then'
varop ::= VARID|'!'|'?'
unop ::= '!'|'?'
varid ::= VARID
varidkw ::= VARID|'data'|'type'|'native'|'pure'|'module'|'import'
words ::= VARID words?
word ::= VARID
GETS ::= '<-'
THEN ::= 'then'
CONID ::= (UppercaseLetter|'_') (Letter|Digit|'_'|"'")*
IF ::= 'if'
DCOLON ::= '::'
TYPE ::= 'type'
NEWTYPE ::= 'newtype'
ELSE ::= 'else'
PURE ::= 'pure'
UppercaseLetter ::= '«any character in Unicode categories Letter and Uppercase»'
LowercaseLetter ::= '«any character in Unicode categories Letter and not Uppercase»'
NATIVE ::= 'native'
STRCONST ::= '"' ([^"]|'\"') '"'
CASE ::= 'case'
Digit ::= [0-9]
DATA ::= 'data'
QUALIFIER ::= CONID '.'
ARROW ::= '->'
WHERE ::= 'where'
MUTABLE ::= 'mutable'
Letter ::= '«any character in Unicode category: Letter»'
PACKAGE ::= 'module'
IMPORT ::= 'import'
EARROW ::= '=>'
VARID ::= (LowercaseLetter|'_') (Letter|Digit|'_'|"'")*
DOTDOT ::= '..'

